In [1]:
import numpy as np

# 基本操作

In [2]:
a = np.array([1, 2, 3])
print(type(a))
# 维度(一维就只有一个维度，二维就有如(n, m)这样得维度，高维同理)
print(a.shape)
print(a[0], a[1], a[2]) # 访问不同元素
a[0] = 0
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]]) # 二维(这里不要忘了是两个[]嵌套)
print(b.shape)
print(b[0, 0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[0 2 3]
(2, 3)
1


# 创建矩阵

In [3]:
# 矩阵函数

a = np.zeros((5, 5)) # 这里也别忘了是两个()嵌套
print(a)

b = np.ones((5, 5))
print(b)

# 常数矩阵
c = np.full((5, 5), 7)
print(c)

# 单位矩阵
d = np.eye(5)
print(d)

# 随机数矩阵
e = np.random.random((5, 5))
print(e)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.60221253 0.66178332 0.77857768 0.60382713 0.06417951]
 [0.28570422 0.16869901 0.87171842 0.988552   0.87796264]
 [0.87724836 0.97435563 0.09027111 0.97954867 0.03763745]
 [0.00695894 0.25133004 0.92949946 0.95193699 0.83070219]
 [0.33295312 0.90004502 0.63727541 0.94062916 0.47727063]]


# 索引

## 切片
矩阵格式<br>
1 2 3 4<br>
5 6 7 8<br>
9 10 11 12<br>

[:2, 1: 3]的意思是<br>
切出前两行<br>
3 - 1列(这里就是后 - 前)<br>
这里切的时候取前不取后

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b = a[:2, 1: 3]

print(a[0, 1])
print(b)
b[0, 0]  = 77
print(a[0, 1])

2
[[2 3]
 [6 7]]
77


#### 两种获取中间行数据的方法
#### 将整数索引与切片混合，得到一个较低等级的矩阵
#### 只使用切片产生一个与原始矩阵相同等级的矩阵

In [5]:
row_r1 = a[1, :]    # 第一种
row_r2 = a[1:2, :]  # 第二种
print(row_r1, row_r1.shape)  # 相当于变成一维矩阵了
print(row_r2, row_r2.shape)  # 这里还是二维矩阵

print()
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape) 

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)

[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


#### 意思就是说：
#### 切除出你想要得矩阵可以直接用整数索引

In [6]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"
# 上面得等效为下面得
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]


#### 通过数组索引

In [7]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)

# 创建索引数组
b = np.array([0, 2, 0, 1])

# 使用b中的索引从a的每一行中选择一个元素
# 这里其实是跟上面的一样的
print(a[np.arange(4), b]) 

# 可以进行运算
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


## 数学

#### 矩阵四则运算(非数学意义上的)

In [8]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# 矩阵各项相加
print(x + y)
print(np.add(x, y))

# 矩阵各项相减
print(x - y)
print(np.subtract(x, y))

# 矩阵各项相乘
print(x * y)
print(np.multiply(x, y))

# 矩阵各项相除
print(x / y)
print(np.divide(x, y))

# 矩阵各项开根号
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


#### 向量内积
p = x1 * y1 + ..... + xn * yn

In [9]:
print(x)
print(y)
print()

v = np.array([9, 10])
w = np.array([11, 12])

# 计算向量内积
print(v.dot(w))
print(np.dot(v, w))
print()

# 同理于矩阵
print(x.dot(v))
print(np.dot(x, v))

print(x.dot(y))
print(np.dot(x, y))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]

219
219

[29. 67.]
[29. 67.]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [10]:
print(x)

print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[1. 2.]
 [3. 4.]]
10.0
[4. 6.]
[3. 7.]


## 广播

对于每一行添加一个常数向量
我们可以按如下方法做
### 第一种
这会凑效; 但是当矩阵 x 非常大时，在Python中计算显式循环可能会很慢。<br>
所以这种方法并**不推荐**使用

In [11]:
# 在x的每一行后添加一个向量v
# 并将结果存到矩阵y中
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)
v = np.array([1, 0, 1])
print()
print(v)
print()
y = np.empty_like(x)   # 创建跟x相同大小的空矩阵

# 每一行都添加v
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### 第二种
注意，向矩阵 x 的每一行添加向量 v 等同于通过垂直堆叠多个 v 副本来形成矩阵 vv，然后执行元素的求和x 和 vv。<br>
我们可以像如下这样实现这种方法：<br>
这里其实是一个用**空间换取时间**的算法

In [12]:
print(x)
print()
print(v)

# 将4个v向量堆叠在一起
vv = np.tile(v, (4, 1))
print()
print(vv)

y = x + vv
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### 第三种
np里面允许我们在不创建多副本的情况下进行运算(可以不用更多的空间换取时间)<br>
这就是**广播**
广播遵循以下原则：
1. 如果数组不具有相同的rank，则将较低等级数组的形状添加1，直到两个形状具有相同的长度。
2. 如果两个数组在维度上具有相同的大小，或者如果其中一个数组在该维度中的大小为1，则称这两个数组在维度上是兼容的。
3. 如果数组在所有维度上兼容，则可以一起广播。
4. 广播之后，每个阵列的行为就好像它的形状等于两个输入数组的形状的元素最大值。
5. 在一个数组的大小为1且另一个数组的大小大于1的任何维度中，第一个数组的行为就像沿着该维度复制一样

In [13]:
print(x)
print(v)

# 使用broadcast进行相加
y = x + v
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
