In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.3'

### np.array

In [5]:
nparr = np.array([i for i in range(100)])

In [6]:
nparr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
nparr.dtype

dtype('int32')

### linspace

In [8]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [9]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [11]:
np.random.randint(0, 10)

6

In [12]:
np.random.randint(0, 10, 10)

array([0, 8, 8, 0, 8, 8, 7, 1, 8, 2])

In [13]:
np.random.randint(4, 8, size=(3, 5))

array([[6, 5, 6, 7, 7],
       [6, 5, 5, 4, 5],
       [6, 7, 4, 5, 6]])

In [ ]:
np.random.seed()