In [8]:
import numpy as np

# 基本操作

In [3]:
a = np.array([1, 2, 3])
print(type(a))
# 维度(一维就只有一个维度，二维就有如(n, m)这样得维度，高维同理)
print(a.shape)
print(a[0], a[1], a[2]) # 访问不同元素
a[0] = 0
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]]) # 二维(这里不要忘了是两个[]嵌套)
print(b.shape)
print(b[0, 0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[0 2 3]
(2, 3)
1


# 创建矩阵

In [7]:
# 矩阵函数

a = np.zeros((5, 5)) # 这里也别忘了是两个()嵌套
print(a)

b = np.ones((5, 5))
print(b)

# 常数矩阵
c = np.full((5, 5), 7)
print(c)

# 单位矩阵
d = np.eye(5)
print(d)

# 随机数矩阵
e = np.random.random((5, 5))
print(e)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.9477381  0.92558953 0.24410223 0.4953216  0.26090443]
 [0.98806913 0.98373477 0.4667734  0.73090304 0.71642852]
 [0.73517835 0.79693692 0.91329338 0.86807194 0.67480962]
 [0.21534385 0.57496304 0.6149117  0.06894214 0.60333022]
 [0.14642873 0.55744271 0.64144791 0.63639868 0.22577419]]


# 索引

## 切片
矩阵格式

1 2 3 4

5 6 7 8

9 10 11 12

[:2, 1: 3]的意思是

切出前两行

3 - 1列(这里就是后 - 前)</br>

这里切的时候取前不取后

In [15]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b = a[:2, 1: 3]

print(a[0, 1])
print(b)
b[0, 0]  = 77
print(a[0, 1])

2
[[2 3]
 [6 7]]
77


In [19]:
# 两种获取中间行数据的方法
# 将整数索引与切片混合，得到一个较低等级的矩阵
# 只使用切片产生一个与原始矩阵相同等级的矩阵
row_r1 = a[1, :]    # 第一种
row_r2 = a[1:2, :]  # 第二种
print(row_r1, row_r1.shape)  # 相当于变成一维矩阵了
print(row_r2, row_r2.shape)  # 这里还是二维矩阵

print()
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape) 

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
