In [4]:
import torch
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

In [9]:
print(torch.empty(5, 3))
print(torch.rand(5, 3))

tensor([[1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39],
        [1.0561e-38, 1.0010e-38, 1.0653e-38],
        [9.9184e-39, 1.0653e-38, 9.6429e-39],
        [8.4490e-39, 1.1112e-38, 9.9184e-39]])
tensor([[0.0630, 0.9511, 0.5068],
        [0.3798, 0.8206, 0.8671],
        [0.5248, 0.7371, 0.7481],
        [0.3524, 0.2645, 0.2696],
        [0.4376, 0.4123, 0.6562]])


In [10]:
print(torch.zeros(5, 3, dtype=torch.long))

x = torch.tensor([5.5, 3])
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])


In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions

print(x.size(), y.size(), z.size())

torch.Size([4, 4])torch.Size([16])torch.Size([2, 8])


In [13]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.3919])
1.3918893337249756


In [15]:
# 当GPU可用时,我们可以运行以下代码
# 我们将使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype

tensor([2.3919], device='cuda:0')
tensor([2.3919], dtype=torch.float64)
